# Setup
name: persik world
tagline:      A responsive theme for your project on GitHub Pages
url: "bjtlr0.github.io"
baseurl:      ""

# Gems
gems:
  - jekyll-paginate

# Plugins
plugins:
  - bundler
  # - rake
  # - public_suffix
  # - addressable
  # - ffi
  # - rb-fsevent
#Others
markdown: kramdown